# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af528e407cffe76ad81a75c45085461c4e5c766b75e24ccc90f803828969cd522af7a04439e1af600fd6030457228a206c3f93412d98af20833c64b93ec11379

test:
  secret_key_base: c95446affa6abc5d2bea25caa7f38075a611dde1e298b127a2adb3241a0fbc23ab264ac9719d21c3443375d229d2e13e18d523d34a5a65405f423c088f824b70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
